"""Report Generation agent.

The LLM drafts prose (phrasing only) grounded in the consensus scores and the
sources' evidence sentences, citing each finding as [n]. The report is then
verified against its own citations: every sentence that cites a source is
re-checked with the same NLI model against THAT source's text. A sentence the
cited source doesn't support is a citation hallucination — it gets flagged and
the LLM is asked to rewrite it to match the source, or drop it.

Without an LLM, a deterministic template report is built from the same data.
The numbered source list is always generated by code, never by the LLM.
"""
from __future__ import annotations

import asyncio
import json
import logging
import re
from dataclasses import dataclass

import numpy as np

from app.ml.nli_model import verify_batch
from app.models.schemas import ConsensusScore, Paper, PaperStance, ResearchReport, SubQuestion, VerificationLabel
from app.orchestrator.state import ResearchState
from app.services.llm_client import complete, llm_description, llm_enabled
from app.services.text import split_sentences

logger = logging.getLogger(__name__)

_MAX_PER_SIDE = 4  # sources shown per side (supporting / refuting) per hypothesis
_PREMISE_SENTENCES = 3  # abstract sentences used as the premise for a citation check

DRAFT_SYSTEM_PROMPT = (
    "You write a short, plain-English evidence report for a research question, using "
    "ONLY the numbered sources you are given. Rules: (1) write exactly ONE sentence per "
    "source describing what that study found, ending with exactly one citation like [2] "
    "(never cite several sources in one sentence, and never claim more than that "
    "source's evidence sentence says); (2) separately, write a 2-3 sentence summary of "
    "the overall balance of evidence with NO citations; (3) if the verdict is 'mixed' or "
    "'insufficient', say so plainly and present both sides; (4) never invent studies, "
    "numbers or sources; (5) do NOT write a sources list. Structure: '## Summary' "
    "(the uncited summary), then one '## <hypothesis>' section listing the per-source "
    "sentences. Output markdown."
)

REVISE_SYSTEM_PROMPT = (
    "Each item is a sentence from an evidence report whose cited source does NOT "
    "support it, with that source's actual text. Rewrite the sentence so it states only "
    "what the source text supports, keeping the same [n] citation. If the source text "
    "says nothing relevant, return an empty string for 'revised' so the sentence is "
    'dropped. Respond ONLY with a JSON array of {"original": ..., "revised": ...}.'
)


@dataclass
class _Cited:
    n: int
    paper: Paper
    stance: PaperStance


@dataclass
class _Section:
    sub_question: SubQuestion
    consensus: ConsensusScore
    supports: list[_Cited]
    refutes: list[_Cited]


def _plan(state: ResearchState) -> tuple[list[_Section], dict[int, _Cited]]:
    """Per-hypothesis sections plus one global [n] numbering for the cited sources."""
    numbering: dict[str, int] = {}
    by_number: dict[int, _Cited] = {}
    sections: list[_Section] = []

    for sq in state.sub_questions:
        cs = next((c for c in state.consensus if c.sub_question_id == sq.id), None)
        if cs is None:
            continue
        sides: dict[VerificationLabel, list[_Cited]] = {}
        for label in (VerificationLabel.SUPPORTS, VerificationLabel.REFUTES):
            top = sorted(
                (s for s in state.paper_stances if s.sub_question_id == sq.id and s.label == label),
                key=lambda s: -s.confidence,
            )[:_MAX_PER_SIDE]
            items = []
            for stance in top:
                paper = state.paper_by_id(stance.paper_id)
                if paper is None:
                    continue
                n = numbering.setdefault(paper.paper_id, len(numbering) + 1)
                cited = _Cited(n=n, paper=paper, stance=stance)
                by_number[n] = cited
                items.append(cited)
            sides[label] = items
        sections.append(_Section(sq, cs, sides[VerificationLabel.SUPPORTS], sides[VerificationLabel.REFUTES]))
    return sections, by_number


def _year(paper: Paper) -> str:
    return str(paper.year) if paper.year else "n.d."


def _balance(cs: ConsensusScore) -> str:
    total = cs.supports + cs.refutes + cs.not_enough_info
    return (
        f"{cs.supports} of {total} papers support it, {cs.refutes} refute it, "
        f"{cs.not_enough_info} take no clear position "
        f"(evidence strength {cs.evidence_strength:.2f}, controversy {cs.controversy_score:.2f})"
    )


def _evidence_context(sections: list[_Section]) -> str:
    lines: list[str] = []
    for sec in sections:
        h = sec.sub_question.hypothesis or sec.sub_question.text
        lines.append(f"\n### Hypothesis: {h}\nverdict: {sec.consensus.verdict}; {_balance(sec.consensus)}")
        for label, items in (("SUPPORTS", sec.supports), ("REFUTES", sec.refutes)):
            for c in items:
                lines.append(
                    f'[{c.n}] {label} — {c.paper.title} ({_year(c.paper)}): "{c.stance.evidence_sentence}"'
                )
    return "\n".join(lines)


def _sources_markdown(by_number: dict[int, _Cited]) -> str:
    if not by_number:
        return ""
    lines = ["## Sources"]
    for n in sorted(by_number):
        p = by_number[n].paper
        lines.append(f"- [{n}] {p.title} ({_year(p)})" + (f" — {p.url}" if p.url else ""))
    return "\n".join(lines)


def _consensus_block(sections: list[_Section]) -> str:
    """Verdict + counts per hypothesis, written by code from the consensus scores —
    never by the LLM, so the numbers in the report can't drift from the data."""
    lines = ["## Consensus"]
    for sec in sections:
        h = sec.sub_question.hypothesis or sec.sub_question.text
        lines.append(f"- **{h}** Verdict: **{sec.consensus.verdict}**. {_balance(sec.consensus)}.")
    return "\n".join(lines)


def _template_body(sections: list[_Section]) -> str:
    parts = ["## Summary"]
    for sec in sections:
        h = sec.sub_question.hypothesis or sec.sub_question.text
        parts.append(f"- **{h}** Verdict: **{sec.consensus.verdict}**. {_balance(sec.consensus)}.")
    for sec in sections:
        h = sec.sub_question.hypothesis or sec.sub_question.text
        parts.append(f"\n## {h}")
        for heading, items in (("Supporting evidence", sec.supports), ("Contradicting evidence", sec.refutes)):
            if items:
                parts.append(f"**{heading}**")
                parts += [f'- {c.paper.title} ({_year(c.paper)}): "{c.stance.evidence_sentence}" [{c.n}]' for c in items]
    return "\n".join(parts)


def _extract_summary(body: str) -> str:
    m = re.search(r"^##\s+Summary\s*\n(.*?)(?=^##\s|\Z)", body, re.DOTALL | re.MULTILINE)
    text = (m.group(1) if m else body).strip()
    return text[:500]


# --- citation self-check -------------------------------------------------------

_CITATION = re.compile(r"\[(\d+)\]")


_LIST_MARKER = re.compile(r"^\s*(?:[-*]|\d+[.)])\s+")


def _report_sentences(markdown: str) -> list[str]:
    """Sentences of the prose, keeping their [n] markers so they can be replaced in
    place. List markers ("1.", "-") are stripped so they never leak into a sentence."""
    prose = re.sub(r"^#+.*$", "", markdown, flags=re.MULTILINE)
    out = []
    for line in prose.split("\n"):
        line = _LIST_MARKER.sub("", line.strip())
        out += [s.strip() for s in re.split(r"(?<=[.!?])\s+(?=[A-Z\[])", line) if len(s.split()) >= 4]
    return out


def _claim_text(sentence: str, paper: Paper) -> str:
    """The sentence as a claim about the source's content: without [n] markers, and
    without the source's own title or year, which its abstract can never contain
    (left in, NLI reads them as unsupported extra content)."""
    text = _CITATION.sub("", sentence)
    if paper.title:
        text = re.sub(re.escape(paper.title), "", text, flags=re.IGNORECASE)
    text = re.sub(r"\(\s*(?:19|20)\d{2}\s*\)", "", text)
    return re.sub(r"\s{2,}", " ", text).strip(" ,;:-")


def _premise_for(cited: _Cited, sentence: str) -> str:
    """The cited source's evidence sentence plus the abstract sentences closest to
    the report sentence — so the check is against what the source actually says."""
    from app.services.hybrid_search import _embedder

    sentences = split_sentences(cited.paper.abstract)
    picked: list[str] = []
    if sentences:
        vecs = _embedder().encode([sentence] + sentences, normalize_embeddings=True, show_progress_bar=False)
        sims = np.asarray(vecs[1:]) @ np.asarray(vecs[0])
        picked = [sentences[i] for i in np.argsort(-sims)[:_PREMISE_SENTENCES]]
    if cited.stance.evidence_sentence and cited.stance.evidence_sentence not in picked:
        picked.insert(0, cited.stance.evidence_sentence)
    return " ".join(picked)


@dataclass
class _Flag:
    sentence: str
    n: int
    label: VerificationLabel
    confidence: float
    premise: str


def _check_citations(draft: str, by_number: dict[int, _Cited]) -> tuple[int, list[_Flag]]:
    """Verify each single-citation sentence against the one source it cites."""
    checks: list[tuple[str, int, str, str]] = []  # (sentence, n, claim, premise)
    for sentence in _report_sentences(draft):
        cited = {int(x) for x in _CITATION.findall(sentence)}
        # One finding, one source. A sentence citing several sources is an aggregate
        # ("three studies found...") that no single source can entail, so judging it
        # source-by-source would flag accurate sentences. Balance statements are
        # covered by the deterministic consensus counts instead.
        if len(cited) == 1 and (n := next(iter(cited))) in by_number:
            claim = _claim_text(sentence, by_number[n].paper)
            checks.append((sentence, n, claim, _premise_for(by_number[n], claim)))

    results = verify_batch([(premise, claim) for _s, _n, claim, premise in checks])
    flags = [
        _Flag(sentence, n, r.label, r.confidence, premise)
        for (sentence, n, _claim, premise), r in zip(checks, results)
        if r.label != VerificationLabel.SUPPORTS
    ]
    return len({c[0] for c in checks}), flags


async def _revise(draft: str, flags: list[_Flag], by_number: dict[int, _Cited]) -> tuple[str, list[str]]:
    items = [
        {"original": f.sentence, "source": f"[{f.n}] {by_number[f.n].paper.title}", "source_text": f.premise[:900]}
        for f in flags
    ]
    notes: list[str] = []
    try:
        raw = await complete(REVISE_SYSTEM_PROMPT, json.dumps(items, indent=2), max_tokens=900)
        match = re.search(r"\[.*\]", raw, re.DOTALL)
        revisions = json.loads(match.group(0)) if match else []
    except Exception as exc:  # noqa: BLE001 - keep the draft; just record what was flagged
        logger.warning("report_generation: revision step failed (%r); keeping draft", exc)
        return draft, [f"Flagged, not revised (LLM unavailable): {f.sentence}" for f in flags]

    revised_draft = draft
    for r in revisions:
        if not isinstance(r, dict):  # small models sometimes return a list of bare strings
            continue
        original, revised = str(r.get("original", "")), str(r.get("revised", "")).strip()
        if original and original in revised_draft:
            revised_draft = revised_draft.replace(original, revised)
            notes.append(f'Revised: "{original}" -> "{revised}"' if revised else f'Removed (unsupported by its source): "{original}"')
    return re.sub(r"[ \t]{2,}", " ", revised_draft), notes


async def _generate(state: ResearchState, sections: list[_Section], by_number: dict[int, _Cited]) -> ResearchReport:
    draft = await complete(
        DRAFT_SYSTEM_PROMPT,
        f'Research question: "{state.question}"\n\nSources:\n{_evidence_context(sections)}',
        max_tokens=1500,
    )
    notes: list[str] = []
    body = draft
    checked, flags = 0, []
    try:
        checked, flags = _check_citations(draft, by_number)
        if flags:
            body, notes = await _revise(draft, flags, by_number)
            for f in flags:
                notes.insert(0, f"Flagged: [{f.n}] did not support the sentence ({f.label.value} {f.confidence:.2f}): {f.sentence}")
    except Exception as exc:  # noqa: BLE001 - the draft is still worth returning
        logger.warning("report_generation: self-check failed (%r); returning the unchecked draft", exc)
        body, notes = draft, [f"Self-check could not run: {exc!r}"]

    body = body.strip()
    sources = _sources_markdown(by_number)
    return ResearchReport(
        question=state.question,
        summary=_extract_summary(body),
        body_markdown=_consensus_block(sections) + "\n\n" + body + ("\n\n" + sources if sources else ""),
        revised=bool(flags),
        revision_notes=notes,
        generated_by=llm_description(),
        checked_sentences=checked,
        flagged_sentences=len({f.sentence for f in flags}),
    )


def _template_report(state: ResearchState, sections: list[_Section], by_number: dict[int, _Cited]) -> ResearchReport:
    body = _template_body(sections)
    sources = _sources_markdown(by_number)
    return ResearchReport(
        question=state.question,
        summary=_extract_summary(body),
        body_markdown=body + ("\n\n" + sources if sources else ""),
    )


def run(state: ResearchState) -> None:
    sections, by_number = _plan(state)
    if llm_enabled() and sections:
        try:
            state.report = asyncio.run(_generate(state, sections, by_number))
            return
        except Exception as exc:  # noqa: BLE001 - LLM is phrasing help only; never fail the query over it
            logger.warning("report_generation: LLM draft failed (%r); using template report", exc)
    state.report = _template_report(state, sections, by_number)
